int a = 10;
int b = 3;
int c = 6;
int d = 5;
int e = 8;
int max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("max = ");
Console.WriteLine(max);